//State de productos
export const  OBTENER_PRODUCTOS_EXITO  = "OBTENER_PRODUCTOS_EXITO "
// State para el Pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ODENADO';

//State del cliente
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';
export const ACTUALIZAR_RECOMENDADOS = 'ACTUALIZAR_RECOMENDADOS';
